version: '3.8'

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4320:4317"   # OTLP gRPC receiver (changed to 4320 to avoid conflict with tempo)
      - "4319:4318"   # OTLP HTTP receiver (changed to 4319 to avoid conflict)
      - "8889:8889"   # Prometheus metrics
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - observability

  # Prometheus for metrics storage
  prometheus:
    image: prom/prometheus:v2.48.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - observability

  # Tempo for trace storage
  tempo:
    image: grafana/tempo:2.3.1
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"   # Tempo
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - observability

  # Loki for log storage
  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - observability

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.2.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - observability

  # PostgreSQL for data persistence
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: observability
      POSTGRES_USER: observability
      POSTGRES_PASSWORD: observability123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - observability

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - observability

  test-app:
    image: test-app:1.0.0-man-inst
    environment:
      - PORT=8080
      - OTEL_SERVICE_NAME=test-app
      # 明确使用HTTP导出器，而不是默认的gRPC导出器
      - OTEL_TRACES_EXPORTER=otlphttp
      - OTEL_METRICS_EXPORTER=otlphttp
      - OTEL_LOGS_EXPORTER=otlphttp
      # 设置HTTP导出器的端点
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # 为每种导出类型明确设置端点和协议
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://otel-collector:4318/v1/logs
      - OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/protobuf
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_PYTHON_LOG_CORRELATION=true
      - PYTHONPATH=/app:/auto-instrumentation
#      - PYTHONPATH="/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation:/otel-auto-instrumentation"
    volumes:
      - ./:/auto-instrumentation
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
    networks:
      - observability
    # Run the application with auto-instrumentation
    command: python /app/test_app.py

volumes:
  prometheus_data:
  tempo_data:
  loki_data:
  grafana_data:
  postgres_data:
  redis_data:

networks:
  observability:
    driver: bridge
