receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  resource:
    attributes:
      - key: deployment.environment
        value: local-testing
        action: upsert

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: 0.0.0.0:8889
  
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
      
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 500ms
      max_interval: 5s
      max_elapsed_time: 30s
    sending_queue:
      enabled: true
      queue_size: 1000
      num_consumers: 2

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [loki, debug]