apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: custom-instrumentation
  namespace: default
spec:
  # Global exporter configuration
  exporter:
    endpoint: http://otel-collector.observability.svc.cluster.local:4317
    
  # Propagators for distributed tracing
  propagators:
    - tracecontext
    - baggage
    - b3
    
  # Sampling configuration
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"  # Sample 25% of traces
  
  # Resource attributes (applied to all telemetry)
  resource:
    addK8sUIDAttributes: true
    resourceAttributes:
      deployment.environment: production
      service.namespace: saas-engine
  
  # Python-specific configuration using our custom image
  python:
    # The image tag will be selected based on the Python version in the pod annotation
    image: ${OTEL_PYTHON_IMAGE:custom-otel-autoinstrumentation-python:1.0.0}
    env:
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: "true"
      - name: OTEL_PYTHON_LOG_CORRELATION
        value: "true"
      # Add Python version detection
      - name: PYTHON_VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['instrumentation.opentelemetry.io/python-version']