# Calendar Service Configuration
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: calendar-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar_service
    username: calendar_user
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
    open-in-view: false

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# Calendar Service Specific Configuration
calendar-service:
  cache:
    ttl: PT24H
    max-entries: 100000
  
  external-apis:
    holiday-api:
      url: "https://api.holidayapi.com"
      timeout: 5s
      retry-attempts: 3
    
    government-sources:
      enabled: true
      sources:
        - country: "US"
          url: "https://api.usa.gov/holidays"
        - country: "GB"
          url: "https://api.gov.uk/bank-holidays"
  
  database:
    holiday-cache-refresh-interval: PT6H

  performance:
    bulk-request-limit: 1000
    max-search-days: 30

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.feng.calendar: INFO
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/calendar-service.log
