# Test Configuration for Calendar Service
spring:
  # Test Database Configuration (H2 in-memory)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Test JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # Test Redis Configuration (embedded)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1s

  # Disable Flyway for tests
  flyway:
    enabled: false

# Test Calendar Service Configuration
calendar-service:
  cache:
    ttl: PT1H
    max-entries: 1000
  external-apis:
    holiday-api:
      timeout: 1s
      retry-attempts: 1
  performance:
    bulk-request-limit: 100
    max-search-days: 10

# Test Logging
logging:
  level:
    com.feng.calendar: DEBUG
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
