# Production Configuration for Calendar Service
spring:
  # Production Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://prod-db:5432/calendar_service}
    username: ${DATABASE_USERNAME:calendar_user}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Production Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:prod-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl: true
      timeout: 5s
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 5000ms

  # Production JPA Configuration
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true

# Production Calendar Service Configuration
calendar-service:
  external-apis:
    holiday-api:
      timeout: 10s
      retry-attempts: 5
  performance:
    bulk-request-limit: 5000
    max-search-days: 60

# Production Logging
logging:
  level:
    com.feng.calendar: WARN
    org.springframework.cache: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/calendar-service/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

# Production Management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
