# Global settings
namespace: default
environment: development

instrumentation:
  enabled: true
  name: custom-instrumentation
  namespace: default
  exporters:
    - endpoint: "http://otel-collector.observability.svc.cluster.local:4317"
      protocol: "grpc"
    - endpoint: "http://otel-collector.observability.svc.cluster.local:4318/v1/traces"
      protocol: "http"
    # Add additional exporters as needed, for example:
    # - endpoint: "http://second-collector.observability.svc.cluster.local:4317"
    #   protocol: "grpc"
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.5"
  resource:
    addK8sUIDAttributes: true
    resourceAttributes:
      deployment.environment: development
      service.namespace: saas-engine
  python:
    image: custom-otel-autoinstrumentation-python:1.0.0
    env:
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
      OTEL_PYTHON_LOG_CORRELATION: "true"

operator:
  enabled: false
  namespace: opentelemetry-operator-system
  replicas: 1
  image: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.136.0
  kubeRbacProxyImage: quay.io/brancz/kube-rbac-proxy:v0.13.1
  zapLogLevel: info
  enableNginx: true
  resources:
    requests:
      cpu: 50m
      memory: 32Mi

collector:
  enabled: false
  name: otel-collector
  namespace: observability
  replicas: 1
  image: otel/opentelemetry-collector-contrib:0.91.0
  resources: {}
  exporters:
    logging:
      enabled: true
      verbosity: detailed
    otlp:
      enabled: true
      endpoint: jaeger:14250
      tls:
        insecure: true
    prometheus:
      enabled: true
      endpoint: 0.0.0.0:8889
  processors:
    batch:
      timeout: 1s
      sendBatchSize: 1024
    memoryLimiter:
      checkInterval: 1s
      limitMiB: 1000
      spikeLimitMiB: 200

# Optional test application to validate instrumentation end-to-end
testApp:
  enabled: false
  name: test-app
  replicas: 1
  image: test-app:latest
  port: 8080
  serviceName: test-app
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi