apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      
      # Collect host metrics
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu:
          memory:
          disk:
          network:
          filesystem:
      
      # Kubernetes metrics
      kubeletstats:
        collection_interval: 30s
        auth_type: "serviceAccount"
        endpoint: "https://${K8S_NODE_NAME}:10250"
        insecure_skip_verify: true

    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
      
      resource:
        attributes:
          - key: cluster.name
            value: observability-cluster
            action: insert
          - key: k8s.node.name
            from_attribute: k8s.node.name
            action: insert
      
      resourcedetection:
        detectors: [gcp, env, system]
        timeout: 5s
      
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: K8S_NODE_NAME
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.node.name
            - k8s.container.name
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

    exporters:
      # Forward to gateway collector
      otlp:
        endpoint: otel-collector-gateway:4317
        tls:
          insecure: true
      
      # Direct export to Prometheus
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: otel
        const_labels:
          cluster: observability-cluster

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, resource, resourcedetection, batch]
          exporters: [otlp]
        
        metrics:
          receivers: [otlp, hostmetrics, kubeletstats]
          processors: [k8sattributes, resource, resourcedetection, batch]
          exporters: [otlp, prometheus]
        
        logs:
          receivers: [otlp]
          processors: [k8sattributes, resource, resourcedetection, batch]
          exporters: [otlp]
