server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: data-collector-service
  
  profiles:
    active: development

# OpenTelemetry Configuration
otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      protocol: grpc
  service:
    name: ${spring.application.name}
    version: ${service.version:1.0.0}
  resource:
    attributes:
      deployment.environment: ${deployment.environment:development}

# Logging Configuration
logging:
  level:
    com.feng.observability: DEBUG
    io.opentelemetry: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Application specific configuration
service:
  version: 1.0.0
  environment: development

# Async configuration
spring:
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
        thread-name-prefix: telemetry-async-
      thread-name-prefix: telemetry-scheduling-
    scheduling:
      pool:
        size: 2
